doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        dbname: test-roy
        host: localhost
        port: 3306
        user: test-user
        password: 12345
        driver: pdo_mysql
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
